 [package]
 name = "nautilus-enclave"
 version = "0.1.0"
 edition = "2021"

 [lib]
 crate-type = ["rlib"]

 [[bin]]
 name = "nautilus-enclave"
 path = "src/main.rs"

 [dependencies]
 nautilus-shared = { path = "../shared" }
 serde_json = "1"

