 [package]
 name = "sui-vm"
 version = "0.1.0"
 edition = "2021"

[dependencies]
sui-core = { path = "../core" }
sui-storage = { path = "../storage" }
serde_json = "1"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
anyhow = "1"

