 [package]
 name = "aws-nautilus-sdk"
 version = "0.1.0"
 edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
aws-config = "1"
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", features = ["v4"] }

